/**
 * Shell integration: a zsh hook sourced from ~/.zshenv points TMPDIR and Xcode build output
 * at the lane of the checkout a command runs in. Providers run every command through the
 * user's shell, so this covers all of them without touching upstream.
 *
 * Helpers in the shims folder record leases in the lane's `leases.tsv` (`lane-run` processes,
 * simulators made with `xcrun simctl create|clone`) and share the machine's build slots
 * (`lane-slot`, which xcodebuild uses for heavy actions).
 */
import { PORT_BLOCK } from "./policy.ts";

export const PROFILE_BEGIN = "# >>> loom lanes >>>";
export const PROFILE_END = "# <<< loom lanes <<<";

export const shellDir = (lanesRoot: string) => `${lanesRoot}/.loom`;
export const shimsDir = (lanesRoot: string) => `${shellDir(lanesRoot)}/shims`;
export const slotsDir = (lanesRoot: string) => `${shellDir(lanesRoot)}/slots`;
/** The lease ledger beside a lane's space; outside the image so it survives detaching. */
export const ledgerPath = (laneDir: string) => `${laneDir}/leases.tsv`;
export const SHIMS = ["xcodebuild", "xcrun", "lane-run", "lane-slot"] as const;

const quote = (value: string) => `'${value.replaceAll("'", `'\\''`)}'`;

/** Tabs and newlines would break the index; such paths are left unrouted. */
const indexable = (value: string) => !/[\t\n\r]/.test(value);

/** One line per checkout path: checkout, space, lane id, first port. */
export const renderIndex = (
  lanes: ReadonlyArray<{
    readonly checkoutPaths: ReadonlyArray<string>;
    readonly spacePath: string;
    readonly laneId: string;
    readonly portBase: number;
  }>,
) =>
  lanes
    .flatMap((lane) =>
      indexable(lane.spacePath) && indexable(lane.laneId)
        ? [...new Set(lane.checkoutPaths)]
            .filter(indexable)
            .map((checkout) => `${checkout}\t${lane.spacePath}\t${lane.laneId}\t${lane.portBase}\n`)
        : [],
    )
    .join("");

export const renderHook = (
  lanesRoot: string,
) => `# Generated by Loom (project lifecycle). Loom rewrites this file; do not edit it.
# Points TMPDIR and Xcode build output at the lane of the checkout containing $PWD.
typeset -g _loom_lanes_dir=${quote(shellDir(lanesRoot))}

_loom_lane_apply() {
  emulate -L zsh
  local checkout space lane port best= best_space= best_lane= best_port= here=$PWD real=\${PWD:A}
  local shims=$_loom_lanes_dir/shims
  if [[ -r $_loom_lanes_dir/lanes.tsv ]]; then
    while IFS=$'\\t' read -r checkout space lane port; do
      [[ -n $checkout && \${#checkout} -gt \${#best} ]] || continue
      if [[ $here == "$checkout" || $here == "$checkout"/* || $real == "$checkout" || $real == "$checkout"/* ]]; then
        best=$checkout
        best_space=$space
        best_lane=$lane
        best_port=$port
      fi
    done < $_loom_lanes_dir/lanes.tsv
  fi
  if [[ -n $best_space && -d $best_space/tmp && -w $best_space/tmp ]]; then
    [[ -n \${LOOM_LANE_SPACE-} ]] || typeset -gx LOOM_LANE_SAVED_TMPDIR=\${TMPDIR-}
    typeset -gx LOOM_LANE_CHECKOUT=$best LOOM_LANE_SPACE=$best_space
    typeset -gx LOOM_LANE_TMP=$best_space/tmp LOOM_LANE_BUILD=$best_space/build LOOM_LANE_DATA=$best_space/data
    typeset -gx LOOM_LANE_ID=$best_lane LOOM_LANE_LEASES=\${best_space:h}/leases.tsv
    if [[ $best_port == <-> ]]; then
      typeset -gx LOOM_LANE_PORT=$best_port LOOM_LANE_PORTS=$best_port-$(( best_port + ${PORT_BLOCK - 1} ))
    else
      unset LOOM_LANE_PORT LOOM_LANE_PORTS
    fi
    typeset -gx TMPDIR=$best_space/tmp/
    path=($shims \${path:#$shims})
  elif [[ -n \${LOOM_LANE_SPACE-} ]]; then
    if [[ -n \${LOOM_LANE_SAVED_TMPDIR-} ]]; then
      typeset -gx TMPDIR=$LOOM_LANE_SAVED_TMPDIR
    else
      unset TMPDIR
    fi
    unset LOOM_LANE_SAVED_TMPDIR LOOM_LANE_CHECKOUT LOOM_LANE_SPACE LOOM_LANE_TMP LOOM_LANE_BUILD LOOM_LANE_DATA
    unset LOOM_LANE_ID LOOM_LANE_LEASES LOOM_LANE_PORT LOOM_LANE_PORTS
    path=(\${path:#$shims})
  fi
}

# Login shells run path_helper after this file and move system paths ahead of the shims,
# so these functions are what reliably route xcodebuild and xcrun.
xcodebuild() {
  if [[ -n \${LOOM_LANE_BUILD-} ]]; then
    "$_loom_lanes_dir/shims/xcodebuild" "$@"
  else
    command xcodebuild "$@"
  fi
}
xcrun() {
  if [[ -n \${LOOM_LANE_BUILD-} ]]; then
    "$_loom_lanes_dir/shims/xcrun" "$@"
  else
    command xcrun "$@"
  fi
}

_loom_lane_apply
if [[ -o interactive ]]; then
  autoload -Uz add-zsh-hook && add-zsh-hook chpwd _loom_lane_apply
fi
`;

/** Sets `real` to the first `name` on PATH outside the shims folder. */
const findReal = (name: string) => `real=
old_ifs=$IFS
IFS=:
for dir in $PATH; do
  [ "$dir" = "$shims" ] && continue
  if [ -x "$dir/${name}" ]; then real=$dir/${name}; break; fi
done
IFS=$old_ifs
[ -n "$real" ] || real=/usr/bin/${name}`;

/** Sets `ledger` to the current lane's lease file, from the hook's variables or the index. */
const findLedger = (
  lanesRoot: string,
) => `if [ -z "\${LOOM_LANE_SPACE:-}" ] && [ -r ${quote(`${shellDir(lanesRoot)}/lanes.tsv`)} ]; then
  LOOM_LANE_SPACE=$(awk -F '\\t' -v a="$(pwd)" -v b="$(pwd -P)" '
    { c = $1; if ((a == c || index(a, c "/") == 1 || b == c || index(b, c "/") == 1) && length(c) > n) { n = length(c); s = $2 } }
    END { print s }' ${quote(`${shellDir(lanesRoot)}/lanes.tsv`)})
fi
ledger=\${LOOM_LANE_LEASES:-}
if [ -z "$ledger" ] && [ -n "\${LOOM_LANE_SPACE:-}" ]; then ledger=\${LOOM_LANE_SPACE%/space}/leases.tsv; fi
clean() { printf '%s' "$*" | tr '\\t\\n\\r' '   ' | cut -c1-200; }`;

/** Process start time as ps prints it; with the pid it identifies one process. */
const START_TIME = `$(LC_ALL=C ps -o lstart= -p $$ | tr -s ' ' | sed 's/^ //')`;

/** Actions that compile; they wait for a build slot. */
const HEAVY_ACTIONS = "build|test|build-for-testing|archive|analyze|docbuild|install";

export const renderXcodebuildShim = (lanesRoot: string) => `#!/bin/sh
# Generated by Loom (project lifecycle). Sends Xcode build output into the current lane and
# runs compiling actions in one of the machine's build slots.
shims=${quote(shimsDir(lanesRoot))}
${findReal("xcodebuild")}
if [ -z "\${LOOM_LANE_BUILD:-}" ] || [ ! -w "$LOOM_LANE_BUILD" ]; then exec "$real" "$@"; fi

derived=
packages=
build=
heavy=
previous=
for arg in "$@"; do
  case $previous in
    -derivedDataPath) derived=$arg ;;
    -clonedSourcePackagesDirPath) packages=$arg ;;
  esac
  case $arg in
    build|test|build-for-testing|test-without-building|archive|analyze|clean|docbuild|install|installsrc|-showBuildSettings|-resolvePackageDependencies) build=1 ;;
  esac
  case $arg in
    ${HEAVY_ACTIONS}) heavy=1 ;;
  esac
  previous=$arg
done
[ -n "$build" ] || exec "$real" "$@"

# A /tmp path that does not exist yet becomes a link into the lane.
redirect() {
  case $1 in
    /tmp/*|/private/tmp/*)
      if [ ! -e "$1" ] && [ ! -L "$1" ] && [ -d "$(dirname "$1")" ]; then
        target="$LOOM_LANE_BUILD/redirect/$(printf '%s' "$1" | tr '/' '_')"
        mkdir -p "$target" && ln -s "$target" "$1"
      fi
      ;;
  esac
}
[ -n "$derived" ] && redirect "$derived"
[ -n "$packages" ] && redirect "$packages"
[ -n "$packages" ] || set -- -clonedSourcePackagesDirPath "$LOOM_LANE_BUILD/SourcePackages" "$@"
[ -n "$derived" ] || set -- -derivedDataPath "$LOOM_LANE_BUILD/DerivedData" "$@"
[ -n "$heavy" ] && exec "$shims/lane-slot" "$real" "$@"
exec "$real" "$@"
`;

export const renderXcrunShim = (lanesRoot: string) => `#!/bin/sh
# Generated by Loom (project lifecycle). Routes xcrun xcodebuild through the lane's shim and
# records simulators made with simctl create or clone as leases of the current lane.
shims=${quote(shimsDir(lanesRoot))}
${findReal("xcrun")}
case "\${1:-}" in
  xcodebuild) shift; exec "$shims/xcodebuild" "$@" ;;
  simctl) ;;
  *) exec "$real" "$@" ;;
esac
case "\${2:-}" in
  create) name=\${3:-} ;;
  clone) name=\${4:-} ;;
  *) exec "$real" "$@" ;;
esac
${findLedger(lanesRoot)}
[ -n "$ledger" ] || exec "$real" "$@"
out=$("$real" "$@")
status=$?
[ -n "$out" ] && printf '%s\\n' "$out"
udid=$(printf '%s\\n' "$out" | tail -n 1 | tr -d '[:space:]')
if [ "$status" -eq 0 ]; then
  case $udid in
    *[!0-9A-Fa-f-]*|'') ;;
    *) printf 'simulator\\t%s\\t%s\\t%s\\n' "$udid" "$(clean "$name")" "$(date +%s)" >> "$ledger" ;;
  esac
fi
exit "$status"
`;

export const renderRunShim = (lanesRoot: string) => `#!/bin/sh
# Generated by Loom (project lifecycle). Runs a command as a process the current lane owns.
# Loom stops it, and the processes it started, when the lane is released. --detach starts it in
# the background, in its own process group and ignoring hangups, so it outlives the shell or
# agent command that started it.
usage() { echo "usage: lane-run [--name NAME] [--detach [--log FILE]] [--] command [args...]" >&2; exit 64; }
self=${quote(`${shimsDir(lanesRoot)}/lane-run`)}
name=
detach=
log=
while [ $# -gt 0 ]; do
  case $1 in
    --name) [ $# -ge 2 ] || usage; name=$2; shift 2 ;;
    --detach) detach=1; shift ;;
    --log) [ $# -ge 2 ] || usage; log=$2; shift 2 ;;
    --) shift; break ;;
    *) break ;;
  esac
done
[ $# -gt 0 ] || usage
${findLedger(lanesRoot)}
if [ -z "$ledger" ] || [ ! -w "$(dirname "$ledger")" ]; then
  ledger=
  echo "lane-run: not inside a lane checkout, so Loom will not stop this process." >&2
fi
if [ -n "$detach" ]; then
  if [ -z "$log" ]; then
    dir=\${TMPDIR:-/tmp}
    [ -n "$ledger" ] && [ -d "$(dirname "$ledger")/space/tmp" ] && dir="$(dirname "$ledger")/space/tmp"
    log="\${dir%/}/lane-run-$(printf '%s' "\${name:-$1}" | tr -c 'A-Za-z0-9._-' '-' | cut -c1-60).log"
  fi
  # set -m gives the job its own process group; bash's setpgid race notice is not an error.
  pid=$(exec 2>/dev/null; set -m; nohup "$self" --name "\${name:-$*}" -- "$@" >> "$log" 2>&1 < /dev/null & echo $!)
  echo "lane-run: started $pid (log: $log)"
  exit 0
fi
[ -z "$ledger" ] || printf 'process\\t%s\\t%s\\t%s\\n' "$$" "$(clean "\${name:-$*}")" "${START_TIME}" >> "$ledger"
exec "$@"
`;

export const renderSlotShim = (lanesRoot: string) => `#!/bin/sh
# Generated by Loom (project lifecycle). Runs a command in one of the machine's build slots,
# waiting while every slot is busy. The slot frees itself when the command exits.
slots=${quote(slotsDir(lanesRoot))}
self=${quote(`${shimsDir(lanesRoot)}/lane-slot`)}
if [ "\${1:-}" = --held ]; then
  shift
  : > "$LOOM_SLOT_MARKER"
  printf '%s\\t%s\\t%s\\t%s\\n' "$$" "${START_TIME}" "\${LOOM_LANE_SPACE:-}" "$(printf '%s' "$*" | tr '\\t\\n\\r' '   ' | cut -c1-200)" > "$slots/$LOOM_SLOT_INDEX.holder"
  export LOOM_SLOT_HELD=$LOOM_SLOT_INDEX
  unset LOOM_SLOT_MARKER LOOM_SLOT_INDEX
  exec "$@"
fi
[ $# -gt 0 ] || { echo "usage: lane-slot command [args...]" >&2; exit 64; }
# A build started from inside a slot does not take a second one.
[ -z "\${LOOM_SLOT_HELD:-}" ] || exec "$@"
if [ -x /usr/bin/lockf ]; then
  lock="/usr/bin/lockf -k -t 0"
elif command -v flock >/dev/null 2>&1; then
  lock="flock -n -E 75"
else
  exec "$@"
fi
count=$(cat "$slots/count" 2>/dev/null)
case $count in ''|*[!0-9]*) count=2 ;; esac
mkdir -p "$slots"
marker=$(mktemp "\${TMPDIR:-/tmp}/lane-slot.XXXXXX") || exit 1
rm -f "$marker"
export LOOM_SLOT_MARKER=$marker
waiting=
while :; do
  i=1
  while [ "$i" -le "$count" ]; do
    LOOM_SLOT_INDEX=$i
    export LOOM_SLOT_INDEX
    $lock "$slots/$i.lock" "$self" --held "$@"
    status=$?
    if [ -e "$marker" ]; then rm -f "$marker"; exit "$status"; fi
    [ "$status" -eq 75 ] || exit "$status"
    i=$((i + 1))
  done
  if [ -z "$waiting" ]; then
    echo "lane-slot: all $count build slots are busy; waiting for one." >&2
    waiting=1
  fi
  sleep 2
done
`;

/** Every shim's file name and contents. */
export const renderShims = (lanesRoot: string) => ({
  xcodebuild: renderXcodebuildShim(lanesRoot),
  xcrun: renderXcrunShim(lanesRoot),
  "lane-run": renderRunShim(lanesRoot),
  "lane-slot": renderSlotShim(lanesRoot),
});

const profileBlock = (lanesRoot: string) => {
  const hook = quote(`${shellDir(lanesRoot)}/lanes.zsh`);
  return `${PROFILE_BEGIN}\n[[ -r ${hook} ]] && source ${hook}\n${PROFILE_END}\n`;
};

const blockPattern = /^# >>> loom lanes >>>\n[\s\S]*?^# <<< loom lanes <<<\n?/m;

export const hasProfileBlock = (profile: string) => blockPattern.test(profile);

/** Adds or replaces Loom's block in place, leaving every other line as it was. */
export const addProfileBlock = (profile: string, lanesRoot: string) =>
  hasProfileBlock(profile)
    ? profile.replace(blockPattern, () => profileBlock(lanesRoot))
    : `${profile === "" || profile.endsWith("\n") ? profile : `${profile}\n`}${profileBlock(lanesRoot)}`;

/** Removes exactly the lines Loom added. */
export const removeProfileBlock = (profile: string) => profile.replace(blockPattern, "");
