/**
 * Shell integration: a zsh hook sourced from ~/.zshenv points TMPDIR and Xcode build output
 * at the lane of the checkout a command runs in. Providers run every command through the
 * user's shell, so this covers all of them without touching upstream.
 */

export const PROFILE_BEGIN = "# >>> loom lanes >>>";
export const PROFILE_END = "# <<< loom lanes <<<";

export const shellDir = (lanesRoot: string) => `${lanesRoot}/.loom`;
export const shimsDir = (lanesRoot: string) => `${shellDir(lanesRoot)}/shims`;

const quote = (value: string) => `'${value.replaceAll("'", `'\\''`)}'`;

/** Tabs and newlines would break the index; such paths are left unrouted. */
const indexable = (value: string) => !/[\t\n\r]/.test(value);

export const renderIndex = (
  lanes: ReadonlyArray<{
    readonly checkoutPaths: ReadonlyArray<string>;
    readonly spacePath: string;
  }>,
) =>
  lanes
    .flatMap((lane) =>
      indexable(lane.spacePath)
        ? [...new Set(lane.checkoutPaths)]
            .filter(indexable)
            .map((checkout) => `${checkout}\t${lane.spacePath}\n`)
        : [],
    )
    .join("");

export const renderHook = (
  lanesRoot: string,
) => `# Generated by Loom (project lifecycle). Loom rewrites this file; do not edit it.
# Points TMPDIR and Xcode build output at the lane of the checkout containing $PWD.
typeset -g _loom_lanes_dir=${quote(shellDir(lanesRoot))}

_loom_lane_apply() {
  emulate -L zsh
  local checkout space best= best_space= here=$PWD real=\${PWD:A}
  local shims=$_loom_lanes_dir/shims
  if [[ -r $_loom_lanes_dir/lanes.tsv ]]; then
    while IFS=$'\\t' read -r checkout space; do
      [[ -n $checkout && \${#checkout} -gt \${#best} ]] || continue
      if [[ $here == "$checkout" || $here == "$checkout"/* || $real == "$checkout" || $real == "$checkout"/* ]]; then
        best=$checkout
        best_space=$space
      fi
    done < $_loom_lanes_dir/lanes.tsv
  fi
  if [[ -n $best_space && -d $best_space/tmp && -w $best_space/tmp ]]; then
    [[ -n \${LOOM_LANE_SPACE-} ]] || typeset -gx LOOM_LANE_SAVED_TMPDIR=\${TMPDIR-}
    typeset -gx LOOM_LANE_CHECKOUT=$best LOOM_LANE_SPACE=$best_space
    typeset -gx LOOM_LANE_TMP=$best_space/tmp LOOM_LANE_BUILD=$best_space/build LOOM_LANE_DATA=$best_space/data
    typeset -gx TMPDIR=$best_space/tmp/
    path=($shims \${path:#$shims})
  elif [[ -n \${LOOM_LANE_SPACE-} ]]; then
    if [[ -n \${LOOM_LANE_SAVED_TMPDIR-} ]]; then
      typeset -gx TMPDIR=$LOOM_LANE_SAVED_TMPDIR
    else
      unset TMPDIR
    fi
    unset LOOM_LANE_SAVED_TMPDIR LOOM_LANE_CHECKOUT LOOM_LANE_SPACE LOOM_LANE_TMP LOOM_LANE_BUILD LOOM_LANE_DATA
    path=(\${path:#$shims})
  fi
}

# Login shells run path_helper after this file and move system paths ahead of the shims,
# so the function is what reliably routes xcodebuild.
xcodebuild() {
  if [[ -n \${LOOM_LANE_BUILD-} ]]; then
    "$_loom_lanes_dir/shims/xcodebuild" "$@"
  else
    command xcodebuild "$@"
  fi
}

_loom_lane_apply
if [[ -o interactive ]]; then
  autoload -Uz add-zsh-hook && add-zsh-hook chpwd _loom_lane_apply
fi
`;

export const renderXcodebuildShim = (lanesRoot: string) => `#!/bin/sh
# Generated by Loom (project lifecycle). Sends Xcode build output into the current lane.
shims=${quote(shimsDir(lanesRoot))}
real=
old_ifs=$IFS
IFS=:
for dir in $PATH; do
  [ "$dir" = "$shims" ] && continue
  if [ -x "$dir/xcodebuild" ]; then real=$dir/xcodebuild; break; fi
done
IFS=$old_ifs
[ -n "$real" ] || real=/usr/bin/xcodebuild
if [ -z "\${LOOM_LANE_BUILD:-}" ] || [ ! -w "$LOOM_LANE_BUILD" ]; then exec "$real" "$@"; fi

derived=
packages=
build=
previous=
for arg in "$@"; do
  case $previous in
    -derivedDataPath) derived=$arg ;;
    -clonedSourcePackagesDirPath) packages=$arg ;;
  esac
  case $arg in
    build|test|build-for-testing|test-without-building|archive|analyze|clean|docbuild|install|installsrc|-showBuildSettings|-resolvePackageDependencies) build=1 ;;
  esac
  previous=$arg
done
[ -n "$build" ] || exec "$real" "$@"

# A /tmp path that does not exist yet becomes a link into the lane.
redirect() {
  case $1 in
    /tmp/*|/private/tmp/*)
      if [ ! -e "$1" ] && [ ! -L "$1" ] && [ -d "$(dirname "$1")" ]; then
        target="$LOOM_LANE_BUILD/redirect/$(printf '%s' "$1" | tr '/' '_')"
        mkdir -p "$target" && ln -s "$target" "$1"
      fi
      ;;
  esac
}
[ -n "$derived" ] && redirect "$derived"
[ -n "$packages" ] && redirect "$packages"
[ -n "$packages" ] || set -- -clonedSourcePackagesDirPath "$LOOM_LANE_BUILD/SourcePackages" "$@"
[ -n "$derived" ] || set -- -derivedDataPath "$LOOM_LANE_BUILD/DerivedData" "$@"
exec "$real" "$@"
`;

const profileBlock = (lanesRoot: string) => {
  const hook = quote(`${shellDir(lanesRoot)}/lanes.zsh`);
  return `${PROFILE_BEGIN}\n[[ -r ${hook} ]] && source ${hook}\n${PROFILE_END}\n`;
};

const blockPattern = /^# >>> loom lanes >>>\n[\s\S]*?^# <<< loom lanes <<<\n?/m;

export const hasProfileBlock = (profile: string) => blockPattern.test(profile);

/** Adds or replaces Loom's block in place, leaving every other line as it was. */
export const addProfileBlock = (profile: string, lanesRoot: string) =>
  hasProfileBlock(profile)
    ? profile.replace(blockPattern, () => profileBlock(lanesRoot))
    : `${profile === "" || profile.endsWith("\n") ? profile : `${profile}\n`}${profileBlock(lanesRoot)}`;

/** Removes exactly the lines Loom added. */
export const removeProfileBlock = (profile: string) => profile.replace(blockPattern, "");
