// @effect-diagnostics nodeBuiltinImport:off - A bounded directory walk with readdir.
import * as NodeFSP from "node:fs/promises";
import * as NodePath from "node:path";
import type { AppleContainer } from "@t3tools/contracts/fork";
import * as Effect from "effect/Effect";

export const WALK_MAX_DEPTH = 4;
export const WALK_MAX_ENTRIES = 5_000;

const SKIPPED_DIRECTORIES = new Set(["node_modules", "DerivedData", "build", "Pods", "Carthage"]);

const XCODEGEN_SPECS = new Set(["project.yml", "project.json"]);

const KIND_ORDER: Record<AppleContainer["kind"], number> = {
  workspace: 0,
  xcodegen: 1,
  project: 2,
  package: 3,
};

const baseName = (path: string) => path.slice(path.lastIndexOf("/") + 1);
const dirName = (path: string) => (path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "");
const joined = (dir: string, name: string) => (dir === "" ? name : `${dir}/${name}`);

/** The `name` of an XcodeGen spec, which names the generated `<name>.xcodeproj`. */
export const xcodegenSpecName = (path: string, content: string): string | null => {
  if (path.endsWith(".json")) {
    try {
      const name: unknown = JSON.parse(content)?.name;
      return typeof name === "string" && name.trim() !== "" ? name.trim() : null;
    } catch {
      return null;
    }
  }
  const match = /^name:[ \t]*["']?([^"'\n#]+?)["']?[ \t]*(?:#.*)?$/m.exec(content);
  return match ? match[1]!.trim() : null;
};

/**
 * Containers from workspace-relative paths found by the walk. A project's embedded
 * `project.xcworkspace` is not listed, and a project generated by a listed XcodeGen spec is
 * reached through the spec.
 */
export const classifyContainers = (
  paths: ReadonlyArray<string>,
  specNames: ReadonlyMap<string, string>,
): Array<AppleContainer> => {
  const present = new Set(paths);
  const generated = new Set<string>();
  const containers: Array<AppleContainer> = [];
  for (const path of paths) {
    if (!XCODEGEN_SPECS.has(baseName(path))) continue;
    const name = specNames.get(path);
    const project = name === undefined ? undefined : joined(dirName(path), `${name}.xcodeproj`);
    const exists = project !== undefined && present.has(project);
    if (exists) generated.add(project);
    containers.push({
      kind: "xcodegen",
      path,
      name: name ?? (baseName(dirName(path)) || "XcodeGen"),
      ...(exists ? { generatedProjectPath: project } : {}),
    });
  }
  for (const path of paths) {
    const name = baseName(path);
    if (name.endsWith(".xcworkspace") && !dirName(path).endsWith(".xcodeproj"))
      containers.push({ kind: "workspace", path, name: name.slice(0, -".xcworkspace".length) });
    else if (name.endsWith(".xcodeproj") && !generated.has(path))
      containers.push({ kind: "project", path, name: name.slice(0, -".xcodeproj".length) });
    else if (name === "Package.swift")
      containers.push({ kind: "package", path, name: baseName(dirName(path)) || "Package" });
  }
  return containers.sort(
    (left, right) =>
      left.path.split("/").length - right.path.split("/").length ||
      KIND_ORDER[left.kind] - KIND_ORDER[right.kind] ||
      left.path.localeCompare(right.path),
  );
};

const isCandidate = (name: string, isDirectory: boolean) =>
  isDirectory
    ? name.endsWith(".xcworkspace") || name.endsWith(".xcodeproj")
    : name === "Package.swift" || XCODEGEN_SPECS.has(name);

/** Depth- and entry-limited walk; never descends into bundles, dot or build directories. */
export const walkWorkspace = (cwd: string) =>
  Effect.promise(async () => {
    const paths: Array<string> = [];
    let entries = 0;
    let truncated = false;
    const queue: Array<{ readonly dir: string; readonly depth: number }> = [{ dir: "", depth: 0 }];
    while (queue.length > 0) {
      const { dir, depth } = queue.shift()!;
      const listing = await NodeFSP.readdir(NodePath.join(cwd, dir), { withFileTypes: true }).catch(
        () => [],
      );
      for (const entry of listing) {
        if (++entries > WALK_MAX_ENTRIES) {
          truncated = true;
          break;
        }
        const path = joined(dir, entry.name);
        const isDirectory = entry.isDirectory();
        if (isCandidate(entry.name, isDirectory)) {
          paths.push(path);
          continue;
        }
        if (
          isDirectory &&
          depth + 1 < WALK_MAX_DEPTH &&
          !entry.name.startsWith(".") &&
          !SKIPPED_DIRECTORIES.has(entry.name)
        )
          queue.push({ dir: path, depth: depth + 1 });
      }
      if (truncated) break;
    }
    const specNames = new Map<string, string>();
    for (const path of paths.filter((candidate) => XCODEGEN_SPECS.has(baseName(candidate)))) {
      const content = await NodeFSP.readFile(NodePath.join(cwd, path), "utf8").catch(() => "");
      const name = xcodegenSpecName(path, content.slice(0, 64 * 1024));
      if (name !== null) specNames.set(path, name);
    }
    return { containers: classifyContainers(paths, specNames), truncated };
  });

/** Absolute paths under `root` whose entry name passes `match`, bounded like the workspace walk. */
export const findEntries = (
  root: string,
  match: (name: string, isDirectory: boolean) => boolean,
  maxDepth = 6,
) =>
  Effect.promise(async () => {
    const found: Array<string> = [];
    let entries = 0;
    const queue: Array<{ readonly dir: string; readonly depth: number }> = [
      { dir: root, depth: 0 },
    ];
    while (queue.length > 0 && entries <= WALK_MAX_ENTRIES) {
      const { dir, depth } = queue.shift()!;
      const listing = await NodeFSP.readdir(dir, { withFileTypes: true }).catch(() => []);
      for (const entry of listing) {
        if (++entries > WALK_MAX_ENTRIES) break;
        const path = NodePath.join(dir, entry.name);
        const isDirectory = entry.isDirectory();
        if (match(entry.name, isDirectory)) found.push(path);
        else if (
          isDirectory &&
          depth + 1 < maxDepth &&
          !entry.name.startsWith(".") &&
          !SKIPPED_DIRECTORIES.has(entry.name)
        )
          queue.push({ dir: path, depth: depth + 1 });
      }
    }
    return found;
  });

const strings = (value: unknown): Array<string> =>
  Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];

const parseObject = (json: string): Record<string, unknown> | null => {
  try {
    const parsed: unknown = JSON.parse(json);
    return typeof parsed === "object" && parsed !== null
      ? (parsed as Record<string, unknown>)
      : null;
  } catch {
    return null;
  }
};

/** `xcodebuild -list -json`: `project` for projects, `workspace` (schemes only) for workspaces. */
export const parseSchemeList = (json: string) => {
  const parsed = parseObject(json);
  const info = (parsed?.project ?? parsed?.workspace) as Record<string, unknown> | undefined;
  return {
    schemes: strings(info?.schemes),
    targets: strings(info?.targets),
    configurations: strings(info?.configurations),
  };
};

/** `xcodebuild -showTestPlans -json`: `testPlans` is null when the scheme has none. */
export const parseTestPlans = (json: string) => {
  const plans = parseObject(json)?.testPlans;
  return Array.isArray(plans)
    ? plans.flatMap((plan: unknown) => {
        const name = typeof plan === "string" ? plan : (plan as { name?: unknown } | null)?.name;
        return typeof name === "string" ? [name] : [];
      })
    : [];
};

/** Projects a workspace references, relative to the workspace's folder. */
export const workspaceProjectRefs = (contents: string) =>
  [...contents.matchAll(/location\s*=\s*"(?:group|container):([^"]+\.xcodeproj)"/g)].map(
    (match) => match[1]!,
  );
